### ISSUE TITLE
Problem in generating profile on our exome samples

### ISSUE THREAD

**Issue by mullinyu** [inumanag/aldy#11]
Hi,

I have exome samples by using Illumina exome kit and I got problem in generating profile on trying a few different samples. It's fine to run the bundled test cases.

-bash-4.2$ aldy profile /home/ramsar1971/project/data/RAP028/RAP028-FAT.sorted.markdup.realign.recal.bam > aldy.asd.profile
*** Aldy v2.2.3 (Python 3.6.4, linux) ***
*** (c) 2016-2019 Aldy Authors & Indiana University Bloomington. All rights reserved.
*** Free for non-commercial/academic use only.
Generating profile for DPYD (1:97541297-98388616)
Cannot fetch gene DPYD (1:97541297-98388616)
Generating profile for CYP2C19 (10:96444999-96615001)
Cannot fetch gene CYP2C19 (10:96444999-96615001)
Generating profile for CYP2C9 (10:96690999-96754001)
Cannot fetch gene CYP2C9 (10:96690999-96754001)
Generating profile for CYP2C8 (10:96795999-96830001)
Cannot fetch gene CYP2C8 (10:96795999-96830001)
Generating profile for CYP4F2 (19:15618999-16009501)
Cannot fetch gene CYP4F2 (19:15618999-16009501)
Generating profile for CYP2A6 (19:41347499-41400001)
Cannot fetch gene CYP2A6 (19:41347499-41400001)
Generating profile for CYP2D6 (22:42518899-42553001)
Cannot fetch gene CYP2D6 (22:42518899-42553001)
Generating profile for TPMT (6:18126540-18157375)
Cannot fetch gene TPMT (6:18126540-18157375)
Generating profile for CYP3A5 (7:99244999-99278001)
Cannot fetch gene CYP3A5 (7:99244999-99278001)
Generating profile for CYP3A4 (7:99353999-99465001)
Cannot fetch gene CYP3A4 (7:99353999-99465001)

May I know any advice?

Thanks!

Regards,
Mullin

**Comment by inumanag** [comment]
Hi Mullin,

what is the output of `samtools view -H file.bam`? It could be that either (1) you are not using hg19, or that (2) you have a `chr` prefix.
